import Link from "next/link";
import { Footer, PublicHeader, WirePanel, buttonPrimary, buttonSecondary } from "@/components/wireframe";

const steps = [
  ["01", "Masukkan bahan", "Tempel teks atau URL, atau pilih screenshot percakapan."],
  ["02", "Tinjau proses", "Koreksi hasil OCR dan lihat pemeriksaan apa saja yang dilakukan."],
  ["03", "Ambil tindakan", "Pahami indikator risiko, lalu ikuti langkah yang disarankan."],
];

export default function Home() {
  return <><PublicHeader /><main>
    <section className="border-b border-[var(--border)] bg-[var(--surface)]"><div className="mx-auto grid max-w-[1180px] lg:grid-cols-[1.1fr_.9fr]"><div className="min-w-0 px-5 py-16 sm:py-24 lg:border-r lg:border-[var(--border)] lg:px-12"><p className="inline-block border border-dashed border-[var(--border)] px-2 py-1 font-mono text-[10px] uppercase tracking-wider">wireframe v0.1 · decision support</p><h1 className="mt-7 max-w-2xl text-4xl font-black leading-[1.05] tracking-tight sm:text-6xl">PERIKSA PESAN MENCURIGAKAN SEBELUM BERTINDAK.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[var(--muted)]">CERNO membantu menilai risiko pesan, tautan, dan screenshot dengan alasan yang dapat dipahami serta tindakan yang bisa langsung dilakukan.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/analisis" className={buttonPrimary}>Mulai periksa →</Link><Link href="/panduan" className={buttonSecondary}>Lihat cara kerja</Link></div></div><div className="wf-grid grid min-w-0 min-h-96 place-items-center bg-[var(--subtle)] p-5 sm:p-8"><div className="min-w-0 w-full max-w-md border border-dashed border-[var(--border)] bg-[var(--surface)] p-5"><p className="font-mono text-[10px] uppercase tracking-wider text-[var(--muted)]">[ placeholder hasil analisis ]</p><div className="mt-5 grid grid-cols-[minmax(0,1fr)_80px] items-center gap-3 border-b border-[var(--border)] pb-5"><div className="min-w-0"><p className="text-xs font-bold uppercase">Tingkat risiko</p><p className="mt-1 break-words text-xl font-black sm:text-2xl">MENCURIGAKAN</p></div><div className="grid size-20 place-items-center border-2 border-[var(--border)] font-mono text-xl font-bold">72</div></div><div className="mt-5 space-y-3">{["Tekanan waktu ditemukan", "Domain tidak sesuai institusi", "Pemeriksaan komunitas tersedia"].map((item) => <div key={item} className="flex gap-3 text-sm"><span className="font-mono">[x]</span><span>{item}</span></div>)}</div></div></div></div></section>
    <section className="border-b border-[var(--border)]"><div className="mx-auto grid max-w-[1180px] grid-cols-2 bg-[var(--canvas)] md:grid-cols-4">{[["3", "jenis input"], ["5", "kelompok sinyal"], ["3", "tingkat risiko"], ["1", "tujuan: keputusan aman"]].map(([value,label],i)=><div key={label} className={`px-5 py-6 text-center ${i<3?"border-r border-[var(--border)]":""} ${i<2?"border-b border-[var(--border)] md:border-b-0":""}`}><p className="text-2xl font-black">{value}</p><p className="mt-1 font-mono text-[10px] uppercase text-[var(--muted)]">{label}</p></div>)}</div></section>
    <section className="mx-auto max-w-[1180px] px-5 py-16 sm:py-20"><div className="mx-auto max-w-2xl text-center"><p className="font-mono text-xs font-bold uppercase tracking-wider text-[var(--muted)]">alur utama</p><h2 className="mt-3 text-3xl font-black">TIGA LANGKAH UNTUK BERHENTI DAN MEMERIKSA</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{steps.map(([number,title,copy])=><WirePanel key={number} className="relative p-6"><span className="absolute -top-3 left-4 bg-[var(--ink)] px-2 py-1 font-mono text-xs font-bold text-[var(--surface)]">{number}</span><div className="wf-grid mt-3 grid h-36 place-items-center border border-dashed border-[var(--border)] bg-[var(--subtle)] font-mono text-sm text-[var(--muted)]">[ area interaksi ]</div><h3 className="mt-5 text-lg font-black uppercase">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{copy}</p></WirePanel>)}</div></section>
    <section className="border-t border-[var(--border)] bg-[var(--subtle)]"><div className="mx-auto flex max-w-[1180px] flex-col items-start justify-between gap-6 px-5 py-12 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-black">Menerima pesan yang membuat ragu?</h2><p className="mt-2 text-[var(--muted)]">Jangan klik dulu. Periksa bahan yang Anda terima.</p></div><Link href="/analisis" className={buttonPrimary}>Buka alat analisis</Link></div></section>
  </main><Footer /></>;
}
