import Link from "next/link";
import { AppShell, EmptyState, Metric, PageHeader, Status, WirePanel, buttonPrimary, buttonSecondary, fieldClass } from "@/components/wireframe";

const records = [
  { id: "ANA-0241", type: "Screenshot", preview: "Akun Anda akan diblokir...", risk: "Tinggi", score: "91", time: "10 Sep 2026 · 20:42" },
  { id: "ANA-0238", type: "Teks", preview: "Paket Anda sedang tertahan...", risk: "Mencurigakan", score: "68", time: "09 Sep 2026 · 14:10" },
  { id: "ANA-0229", type: "URL", preview: "ugm.ac.id/pengumuman", risk: "Rendah", score: "12", time: "07 Sep 2026 · 09:21" },
];

export default function HistoryPage() {
  return <AppShell><PageHeader eyebrow="akun · ringkasan" title="Riwayat analisis" description="Hasil yang disimpan hanya menggunakan input teredaksi. Anda dapat membuka detail atau menghapus catatan milik sendiri." action={<Link href="/analisis" className={buttonPrimary}>+ Analisis baru</Link>} /><div className="mx-auto max-w-[1180px] px-5 py-8 sm:px-8"><div className="grid gap-4 sm:grid-cols-3"><Metric value="3" label="Hasil tersimpan" note="30 hari terakhir" /><Metric value="1" label="Risiko tinggi" note="perlu perhatian" /><Metric value="87%" label="Hasil membantu" note="berdasarkan feedback" /></div><WirePanel label="filter riwayat" className="mt-7 p-4"><div className="grid gap-3 md:grid-cols-[1fr_180px_180px_auto]"><label><span className="sr-only">Cari riwayat</span><input className={fieldClass} placeholder="Cari teks teredaksi atau domain..." /></label><label><span className="sr-only">Jenis input</span><select className={fieldClass}><option>Semua input</option><option>Teks</option><option>URL</option><option>Screenshot</option></select></label><label><span className="sr-only">Tingkat risiko</span><select className={fieldClass}><option>Semua risiko</option><option>Rendah</option><option>Mencurigakan</option><option>Tinggi</option></select></label><button type="button" className={buttonSecondary}>Terapkan</button></div></WirePanel><WirePanel label="3 hasil" className="mt-5"><div className="divide-y divide-[var(--border)]">{records.map((record)=><article key={record.id} className="grid gap-4 p-5 hover:bg-[var(--subtle)] md:grid-cols-[110px_1fr_120px_100px_auto] md:items-center"><div><p className="font-mono text-xs font-bold">{record.id}</p><p className="mt-1 text-xs text-[var(--muted)]">{record.type}</p></div><div><p className="font-semibold">{record.preview}</p><p className="mt-1 text-xs text-[var(--muted)]">{record.time}</p></div><Status label={`risiko ${record.risk}`} tone={record.risk === "Tinggi" ? "dark" : record.risk === "Mencurigakan" ? "hatched" : "neutral"} /><p className="font-mono text-sm font-bold">{record.score}/100</p><Link href="/riwayat/detail" className="text-sm font-bold underline underline-offset-4">Buka detail →</Link></article>)}</div></WirePanel><div className="mt-7"><EmptyState title="Contoh keadaan kosong" description="Jika belum ada hasil tersimpan, halaman ini mengarahkan pengguna kembali ke alat analisis dan menjelaskan bahwa akun tidak wajib untuk memeriksa." action={<Link href="/analisis" className={buttonSecondary}>Periksa pesan pertama</Link>} /></div></div></AppShell>;
}
