import Link from "next/link";
import { Footer, PageHeader, PublicHeader, WirePanel, buttonPrimary } from "@/components/wireframe";

const signals = [
  ["Bahasa pesan", "Tekanan waktu, ancaman, permintaan kredensial, pembayaran, atau pola manipulatif lain."],
  ["Struktur URL", "Registered domain, subdomain, punycode, shortener, IP hostname, dan ketidakcocokan merek."],
  ["Threat intelligence", "Pemeriksaan reputasi melalui provider eksternal. Kegagalan provider selalu dinyatakan."],
  ["Sinyal komunitas", "Agregat laporan yang telah melalui redaksi, deduplikasi, pembatasan, dan moderasi."],
  ["Model risiko", "Probabilitas model teks dan URL sebagai bagian dari hasil, bukan satu-satunya penentu."],
];

export default function GuidePage() {
  return <><PublicHeader /><main><PageHeader eyebrow="tentang CERNO" title="Cara kerja dan batas penggunaan" description="Kenali apa yang dianalisis, apa yang disimpan, dan bagaimana membaca hasil sebelum menggunakannya untuk mengambil keputusan." /><div className="mx-auto grid max-w-[1180px] gap-8 px-5 py-10 lg:grid-cols-[.8fr_1.2fr]"><nav className="h-fit border border-[var(--border)] bg-[var(--surface)] p-5 lg:sticky lg:top-5"><p className="font-mono text-xs font-bold uppercase text-[var(--muted)]">di halaman ini</p><ol className="mt-4 space-y-3 text-sm font-semibold"><li><a href="#alur" className="underline underline-offset-4">01 · Alur analisis</a></li><li><a href="#sinyal" className="underline underline-offset-4">02 · Sinyal yang digunakan</a></li><li><a href="#privasi" className="underline underline-offset-4">03 · Privasi dan retensi</a></li><li><a href="#batas" className="underline underline-offset-4">04 · Batas hasil</a></li></ol></nav><div className="space-y-12"><section id="alur"><h2 className="text-2xl font-black">Alur analisis</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["1","Masukkan bahan"],["2","Redaksi & analisis"],["3","Hasil & tindakan"]].map(([n,t])=><WirePanel key={n} className="p-5"><span className="font-mono text-sm font-bold">{n.padStart(2,"0")}</span><p className="mt-8 font-bold">{t}</p></WirePanel>)}</div></section><section id="sinyal"><h2 className="text-2xl font-black">Sinyal yang digunakan</h2><div className="mt-5 border-t border-[var(--border)]">{signals.map(([title,copy],i)=><div key={title} className="grid gap-2 border-b border-[var(--border)] py-5 sm:grid-cols-[40px_180px_1fr]"><span className="font-mono text-xs">0{i+1}</span><h3 className="font-bold">{title}</h3><p className="text-sm leading-6 text-[var(--muted)]">{copy}</p></div>)}</div></section><section id="privasi"><h2 className="text-2xl font-black">Privasi dan retensi</h2><div className="mt-5 border border-[var(--border)] bg-[var(--surface)] p-6"><ul className="space-y-3 text-sm leading-6"><li>• Data sensitif disamarkan sebelum disimpan.</li><li>• Pesan dan screenshot mentah tidak menjadi riwayat secara default.</li><li>• Screenshot berada di penyimpanan privat sementara dan dijadwalkan untuk dihapus.</li><li>• Persetujuan penyimpanan riwayat berbeda dari persetujuan penggunaan data teredaksi.</li></ul></div></section><section id="batas"><h2 className="text-2xl font-black">Batas hasil</h2><p className="mt-4 max-w-[70ch] leading-7 text-[var(--muted)]">CERNO tidak menentukan jenis scam, tidak membuka situs yang diperiksa, dan tidak menyatakan seseorang atau domain sebagai pelaku kriminal. URL yang tidak ditemukan dalam database ancaman belum tentu aman. Selalu verifikasi melalui kanal resmi.</p><Link href="/analisis" className={`${buttonPrimary} mt-6`}>Mulai periksa</Link></section></div></div></main><Footer /></>;
}
